version: '3'
services:
  json-tagger-api:
    build: ./json-tagger-api
    environment:
      - JSONTAGGER_DATA_PATH=/data
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - "${JSONTAGGER_DATA_PATH}:/data"
  json-tagger-react:
    build: ./json-tagger-react
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3000"
    tty: true
    volumes:
      - ./json-tagger-react:/app
      - /app/node_modules
